#!/bin/sh

[ -f /etc/config/aurora ] && exit 0

logger -t aurora "Initializing Aurora theme configuration"

cat > /etc/config/aurora <<EOF
config aurora 'theme'
	option light_background_start 'oklch(0.984 0.003 247.858)'
	option light_background_mid 'oklch(0.968 0.007 247.896)'
	option light_background_end 'oklch(0.929 0.013 255.508)'
	option light_progress_start 'oklch(0.68 0.11 233)'
	option light_progress_end 'oklch(0.7535 0.1034 198.37)'
	option light_primary 'oklch(0.68 0.11 233)'
	option light_primary_text 'oklch(0.6656 0.1055 234.61)'
	option light_muted 'oklch(0.97 0 0)'
	option light_muted_text 'oklch(0.35 0 0)'
	option light_destructive 'oklch(0.94 0.05 25)'
	option light_destructive_text 'oklch(0.35 0.12 25)'
	option light_accent 'oklch(0.62 0.22 25)'
	option light_accent_text 'oklch(0.97 0.02 25)'
	option light_success 'oklch(0.94 0.05 160)'
	option light_success_text 'oklch(0.32 0.09 165)'
	option light_info 'oklch(0.94 0.05 230)'
	option light_info_text 'oklch(0.35 0.08 240)'
	option light_warning 'oklch(0.95 0.05 90)'
	option light_warning_text 'oklch(0.35 0.08 60)'
	option light_error 'oklch(0.94 0.05 25)'
	option light_error_text 'oklch(0.35 0.12 25)'
	option light_default 'oklch(0.97 0 0)'
	option light_default_text 'oklch(0.205 0 0)'
	option dark_background_start 'oklch(0.2077 0.0398 265.75)'
	option dark_background_mid 'oklch(0.3861 0.059 188.42)'
	option dark_background_end 'oklch(0.4318 0.0865 166.91)'
	option dark_progress_start 'oklch(0.4318 0.0865 166.91)'
	option dark_progress_end 'oklch(62.1% 0.145 189.632)'
	option dark_primary 'oklch(0.48 0.118 190.485)'
	option dark_primary_text 'oklch(0.73 0.168 188.745)'
	option dark_muted 'oklch(0.373 0.026 259.733)'
	option dark_muted_text 'oklch(0.82 0.035 259.733)'
	option dark_destructive 'oklch(0.258 0.092 26.042)'
	option dark_destructive_text 'oklch(0.88 0.14 26.042)'
	option dark_accent 'oklch(0.35 0.12 25)'
	option dark_accent_text 'oklch(0.88 0.14 25)'
	option dark_success 'oklch(0.378 0.077 168.94/0.5)'
	option dark_success_text 'oklch(0.92 0.09 160)'
	option dark_info 'oklch(0.391 0.09 240.876/0.5)'
	option dark_info_text 'oklch(0.88 0.06 230)'
	option dark_warning 'oklch(0.414 0.112 45.904/0.5)'
	option dark_warning_text 'oklch(0.924 0.12 95.746)'
	option dark_error 'oklch(0.41 0.159 10.272/0.5)'
	option dark_error_text 'oklch(0.88 0.14 25)'
	option dark_default 'oklch(0.274 0.006 286.033/0.5)'
	option dark_default_text 'oklch(0.985 0.01 285.805)'
	option struct_font_sans '"Lato", ui-sans-serif, system-ui, sans-serif'
	option struct_font_mono 'ui-monospace, "SF Mono", Menlo, Monaco, Consolas, monospace'
	option struct_spacing '0.25rem'
	option nav_submenu_type 'mega-menu'

config toolbar_item
	option title 'Overview'
	option url '/cgi-bin/luci/admin/status/overview'
	option icon 'overview.svg'
	option enabled '1'

config toolbar_item
	option title 'System'
	option url '/cgi-bin/luci/admin/system/system'
	option icon 'system.svg'
	option enabled '1'

config toolbar_item
	option title 'Software'
	option url '/cgi-bin/luci/admin/system/package-manager'
	option icon 'software.svg'
	option enabled '1'

config toolbar_item
	option title 'Network'
	option url '/cgi-bin/luci/admin/network/network'
	option icon 'network.svg'
	option enabled '1'
EOF

exit 0
